
spring.application.name=Tiererkennung


# Default-Port von Ollama ist 11434
# Weitere Optionen siehe https://docs.spring.io/spring-ai/reference/api/chat/ollama-chat.html#_base_properties
spring.ai.ollama.base-url=http://localhost:11434

# Wenn Modell lokal nicht vorhanden, dann soll es NICHT automatisch gepullt werden.
spring.ai.ollama.init.pull-model-strategy=NEVER


# Zur Auswahl stehende Modelle (mit Komma getrennt).
# Das erste Modell ist das Default-Modell.
# Alle in dieser Liste angegebenen Modelle müssen lokal vorhanden sein,
# d.h. sie müssen in der Ausgabe der Liste "ollama list" enthalten sein.
eldecker.ollama.modelle=minicpm-v:8b,moondream,qwen3.5

# minicpm-v:8b - https://ollama.com/library/minicpm-v - ca. 8 GB
# moondream    - https://ollama.com/library/moondream - ca. 1,7 GB
# qwen3.5      - https://ollama.com/library/qwen3.5   - ca. 6,5 GB
