
spring.application.name=Tiererkennung

# Default-Port von Ollama ist 11434
# Weitere Optionen siehe https://docs.spring.io/spring-ai/reference/api/chat/ollama-chat.html#_base_properties
spring.ai.ollama.base-url=http://localhost:11434


# Hier Modell angeben, das mit lokaler Ollama-Instanz schon heruntergeladen wurde
# (es muss in der Ausgabe von "ollama list" auftauchen)


# https://ollama.com/library/qwen3.5
# Größe ca. 6,5 GByte
#spring.ai.ollama.chat.model=qwen3.5

# https://ollama.com/library/minicpm-v (Größe ca. 8 GByte)
spring.ai.ollama.chat.model=minicpm-v:8b
# Fehlermeldung, wenn Model nicht gefunden:
# HTTP 404 - {"error":"model xxxx not found"}

# https://ollama.com/library/moondream
#spring.ai.ollama.chat.model=moondream
# Kleinstes Model (ca. 1,7 GByte) mit "Vision"-Support?


# Wenn Modell lokal nicht vorhanden, dann soll es NICHT automatisch gepullt werden.
# Das Modell soll dann mit dem folgenden Befehl manuell heruntergeladen werden:
# ollama pull <modell-name>
#
# Mit folgendem Modell kann man sich alle lokal vorhandenen Modelle anzeigen lassen:
# ollama list
#
# Heruntergeladenes Modell wieder loeschen: ollama delete <modell-name>
spring.ai.ollama.init.pull-model-strategy=NEVER
